select 
OUTBREAK.DATE_ENTERED "Date",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='India' THEN CURRENT_COUNT END) AS "India Current Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='India' THEN INCREMENTAL_COUNT END) AS "India Incremental Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='India' THEN DELTA END) AS "India Delta",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United States' THEN CURRENT_COUNT END) AS "United States Current Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United States' THEN INCREMENTAL_COUNT END) AS "United States Incremental Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United States' THEN DELTA END) AS "United States Delta",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United Kingdom' THEN CURRENT_COUNT END) AS "United Kingdom Current Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United Kingdom' THEN INCREMENTAL_COUNT END) AS "United Kingdom Incremental Count",
sum(CASE WHEN COUNTRIES.COUNTRY_NAME='United Kingdom' THEN DELTA END) AS "United Kingdom Delta"
from 
(select COUNTRY_CODE,STATE_CODE,CURRENT_COUNT,INCREMENTAL_COUNT,DELTA,RECOVERED,trunc(DATE_ENTERED) DATE_ENTERED,DATE_MODIFIED from outbreak)OUTBREAK 
,COUNTRIES 
,STATES 
WHERE OUTBREAK.STATE_CODE = STATES.STATE_CODE
AND OUTBREAK.COUNTRY_CODE = COUNTRIES.COUNTRY_CODE
AND COUNTRIES.COUNTRY_CODE = STATES.COUNTRY_CODE
GROUP BY OUTBREAK.DATE_ENTERED ORDER BY OUTBREAK.DATE_ENTERED;