CREATE OR REPLACE TABLE COUNTRIES (
COUNTRY_CODE NUMBER INCREMENT,
COUNTRY_NAME CHAR(100),
COUNTRY_DESCRIPTION CHAR(1000),
DATE_ENTERED TIMESTAMP,
DATE_MODIFIED TIMESTAMP,
CONSTRAINT COUNTRY_PK PRIMARY KEY(COUNTRY_CODE));