CREATE OR REPLACE TABLE OUTBREAK (
COUNTRY_CODE NUMBER INCREMENT,
STATE_CODE NUMBER INCREMENT,
CURRENT_COUNT NUMBER,
INCREMENTAL_COUNT NUMBER,
DELTA NUMBER,
RECOVERD NUMBER,
DATE_ENTERED TIMESTAMP,
DATE_MODIFIED TIMESTAMP,
CONSTRAINT STATE_FK_OB FOREIGN KEY(STATE_CODE) REFERENCES STATES(STATE_CODE),
CONSTRAINT COUNTRY_FK_OB FOREIGN KEY(COUNTRY_CODE) REFERENCES COUNTRY(COUNTRY_CODE));