DROP TABLE OUTBREAK;

CREATE TABLE OUTBREAK (
COUNTRY_CODE NUMBER,
STATE_CODE NUMBER,
CURRENT_COUNT NUMBER,
INCREMENTAL_COUNT NUMBER,
DELTA NUMBER,
RECOVERED NUMBER,
DATE_ENTERED TIMESTAMP,
DATE_MODIFIED TIMESTAMP,
CONSTRAINT STATE_FK_OB FOREIGN KEY(STATE_CODE) REFERENCES STATES(STATE_CODE),
CONSTRAINT COUNTRY_FK_OB FOREIGN KEY(COUNTRY_CODE) REFERENCES COUNTRIES(COUNTRY_CODE));
