DROP TABLE STATES;

CREATE TABLE STATES (
STATE_CODE NUMBER GENERATED ALWAYS AS IDENTITY,
COUNTRY_CODE NUMBER,
STATE_NAME CHAR(100),
STATE_DESCRIPTION CHAR(100),
DATE_ENTERED TIMESTAMP,
DATE_MODIFIED TIMESTAMP,
CONSTRAINT STATES_PK PRIMARY KEY(STATE_CODE),
CONSTRAINT COUNTRY_FK FOREIGN KEY(COUNTRY_CODE) REFERENCES COUNTRIES(COUNTRY_CODE));
