CREATE OR REPLACE PACKAGE OUTBREAK_PKG 
AS

PROCEDURE INSERT_NEW_CASES(COUNTRY_NAME_IN IN VARCHAR,STATE_NAME_IN IN VARCHAR,CURRENT_DATE_IN IN DATE,INCREMENTAL_COUNT_IN IN NUMBER,RECOVERED_IN IN NUMBER);

PROCEDURE UPDATE_OLD_CASE(COUNTRY_NAME_IN IN VARCHAR,STATE_NAME_IN IN VARCHAR,CURRENT_COUNT_IN IN NUMBER,INCREMENTAL_COUNT_IN IN NUMBER,RECOVERED_IN IN NUMBER);

END OUTBREAK_PKG;