CREATE OR REPLACE PACKAGE BODY OUTBREAK_PKG AS
PROCEDURE INSERT_NEW_CASES(COUNTRY_NAME_IN IN VARCHAR
	,STATE_NAME_IN IN VARCHAR
	,CURRENT_DATE_IN IN DATE
	,INCREMENTAL_COUNT_IN IN NUMBER
	,RECOVERED_IN IN NUMBER) IS
	
	V_COUNTRY_CODE_IN NUMBER;
	V_STATE_CODE_IN NUMBER;
	V_CURRENT_COUNT_IN NUMBER;
	V_COUNT NUMBER := 0;
	
BEGIN

	DBMS_OUTPUT.PUT_LINE(COUNTRY_NAME_IN);
	DBMS_OUTPUT.PUT_LINE(STATE_NAME_IN);

	select COUNTRY_CODE into V_COUNTRY_CODE_IN from COUNTRIES where country_name=COUNTRY_NAME_IN;

	select STATE_CODE into V_STATE_CODE_IN from STATES where state_name=STATE_NAME_IN;

	select COUNT(*) into V_COUNT 
	from OUTBREAK where 
	COUNTRY_CODE=V_COUNTRY_CODE_IN and 
	STATE_CODE=V_STATE_CODE_IN 
	and DATE_ENTERED = (select max(DATE_ENTERED)-1 from OUTBREAK where COUNTRY_CODE=V_COUNTRY_CODE_IN and STATE_CODE=V_STATE_CODE_IN);

	IF V_COUNT >= 1 THEN
	
		select NVL(CURRENT_COUNT,0) into V_CURRENT_COUNT_IN 
		from OUTBREAK where 
		COUNTRY_CODE=V_COUNTRY_CODE_IN and 
		STATE_CODE=V_STATE_CODE_IN 
		and DATE_ENTERED = (select max(DATE_ENTERED)-1 from OUTBREAK where COUNTRY_CODE=V_COUNTRY_CODE_IN and STATE_CODE=V_STATE_CODE_IN);
		
		INSERT INTO OUTBREAK(COUNTRY_CODE,STATE_CODE,CURRENT_COUNT,INCREMENTAL_COUNT,DELTA,RECOVERED,DATE_ENTERED,DATE_MODIFIED)
		VALUES(V_COUNTRY_CODE_IN
		,V_STATE_CODE_IN
		,(V_CURRENT_COUNT_IN + INCREMENTAL_COUNT_IN)
		,INCREMENTAL_COUNT_IN
		,ABS(V_CURRENT_COUNT_IN - INCREMENTAL_COUNT_IN)
		,RECOVERED_IN
		,CURRENT_DATE_IN
		,NULL);
		
		COMMIT;
	
	ELSE
		V_CURRENT_COUNT_IN := INCREMENTAL_COUNT_IN;
		
		INSERT INTO OUTBREAK(COUNTRY_CODE,STATE_CODE,CURRENT_COUNT,INCREMENTAL_COUNT,DELTA,RECOVERED,DATE_ENTERED,DATE_MODIFIED)
		VALUES(V_COUNTRY_CODE_IN
		,V_STATE_CODE_IN
		,V_CURRENT_COUNT_IN
		,INCREMENTAL_COUNT_IN
		,ABS(V_CURRENT_COUNT_IN - INCREMENTAL_COUNT_IN)
		,RECOVERED_IN
		,CURRENT_DATE_IN
		,NULL);
		
		COMMIT;
		
	END IF;
	

	COMMIT;
	EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('Error found inserting new record');
	DBMS_OUTPUT.PUT_LINE(SQLERRM||SQLCODE);
END INSERT_NEW_CASES;

PROCEDURE UPDATE_OLD_CASE(COUNTRY_NAME_IN IN VARCHAR
		,STATE_NAME_IN IN VARCHAR
		,CURRENT_COUNT_IN IN NUMBER
		,INCREMENTAL_COUNT_IN IN NUMBER
		,RECOVERED_IN IN NUMBER) AS
		
	V_COUNTRY_CODE_IN NUMBER;
	V_STATE_CODE_IN NUMBER;
BEGIN

	select COUNTRY_CODE into V_COUNTRY_CODE_IN from COUNTRIES where country_name=COUNTRY_NAME_IN;
	select STATE_CODE into V_STATE_CODE_IN from STATES where state_name=STATE_NAME_IN;

	UPDATE OUTBREAK SET 
	CURRENT_COUNT 		= CURRENT_COUNT_IN,
	INCREMENTAL_COUNT 	= INCREMENTAL_COUNT_IN
	WHERE COUNTRY_CODE = V_COUNTRY_CODE_IN AND
	STATE_CODE = V_STATE_CODE_IN
	;
	COMMIT;
	EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('Error found updating a record');
	DBMS_OUTPUT.PUT_LINE(SQLERRM||SQLCODE);
END;

END OUTBREAK_PKG;